-- Baseline schema for BillPayWorkerService, generated from the JPA entities.
-- Schema changes go in new V2__..., V3__... files; never edit an applied migration.

CREATE TABLE public.batch_lines (
    line_no integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    batch_id uuid NOT NULL,
    payment_id uuid NOT NULL
);

ALTER TABLE public.batch_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.batch_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.batches (
    created_at timestamp(6) with time zone NOT NULL,
    batch_id uuid NOT NULL,
    status character varying(20) NOT NULL
);

CREATE TABLE public.outbox_event (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    published_at timestamp(6) with time zone,
    state character varying(20) NOT NULL,
    event_key character varying(120) NOT NULL,
    topic character varying(120) NOT NULL,
    payload text NOT NULL
);

ALTER TABLE public.outbox_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.batch_lines
    ADD CONSTRAINT batch_lines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.batches
    ADD CONSTRAINT batches_pkey PRIMARY KEY (batch_id);

ALTER TABLE ONLY public.outbox_event
    ADD CONSTRAINT outbox_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.batch_lines
    ADD CONSTRAINT uk_batch_line_payment UNIQUE (payment_id);

CREATE INDEX idx_batch_line_batch ON public.batch_lines USING btree (batch_id);

CREATE INDEX idx_outbox_state ON public.outbox_event USING btree (state, id);

