-- Baseline schema for SettlementService, generated from the JPA entities.
-- Schema changes go in new V2__..., V3__... files; never edit an applied migration.

CREATE TABLE public.bill_batch_settlement (
    retry_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    next_retry_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    batch_id uuid NOT NULL,
    central_reference character varying(255),
    last_error character varying(255),
    pain001file_name character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT bill_batch_settlement_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'FILE_BUILT'::character varying, 'UPLOADED'::character varying, 'SUBMITTED'::character varying, 'FAILED'::character varying, 'DEAD_LETTERED'::character varying])::text[])))
);

ALTER TABLE public.bill_batch_settlement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bill_batch_settlement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.eft_batch_settlement (
    retry_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    next_retry_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    batch_id uuid NOT NULL,
    cpa005file_name character varying(255),
    last_error character varying(255),
    network_reference character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT eft_batch_settlement_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'FILE_BUILT'::character varying, 'UPLOADED'::character varying, 'SUBMITTED'::character varying, 'FAILED'::character varying, 'DEAD_LETTERED'::character varying])::text[])))
);

ALTER TABLE public.eft_batch_settlement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eft_batch_settlement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.outbox_event (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    published_at timestamp(6) with time zone,
    state character varying(20) NOT NULL,
    event_key character varying(120) NOT NULL,
    topic character varying(120) NOT NULL,
    payload text NOT NULL
);

ALTER TABLE public.outbox_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bill_batch_settlement
    ADD CONSTRAINT bill_batch_settlement_batch_id_key UNIQUE (batch_id);

ALTER TABLE ONLY public.bill_batch_settlement
    ADD CONSTRAINT bill_batch_settlement_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.eft_batch_settlement
    ADD CONSTRAINT eft_batch_settlement_batch_id_key UNIQUE (batch_id);

ALTER TABLE ONLY public.eft_batch_settlement
    ADD CONSTRAINT eft_batch_settlement_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.outbox_event
    ADD CONSTRAINT outbox_event_pkey PRIMARY KEY (id);

CREATE INDEX idx_outbox_state ON public.outbox_event USING btree (state, id);

