-- Baseline schema for PaymentOrchestrator, generated from the JPA entities.
-- Schema changes go in new V2__..., V3__... files; never edit an applied migration.

CREATE TABLE public.outbox (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    key uuid NOT NULL,
    state character varying(20) NOT NULL,
    topic character varying(120) NOT NULL,
    payload_json text NOT NULL
);

ALTER TABLE public.outbox ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payments (
    amount_ccy character varying(3) NOT NULL,
    amount_value numeric(18,2) NOT NULL,
    execution_date date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    batch_id uuid,
    channel character varying(16),
    debtor_account_id uuid NOT NULL,
    external_account_id uuid,
    payment_id uuid NOT NULL,
    state character varying(20) NOT NULL,
    biller_ref_number character varying(64),
    idempotency_key character varying(80) NOT NULL,
    invoice_reference character varying(128),
    external_status_code character varying(255),
    reason character varying(255),
    CONSTRAINT payments_state_check CHECK (((state)::text = ANY ((ARRAY['FUNDS_HELD'::character varying, 'BATCHED'::character varying, 'SUBMITTED'::character varying, 'POSTED'::character varying, 'FAILED'::character varying])::text[])))
);

CREATE TABLE public.processed_events (
    id bigint NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL,
    handler character varying(80) NOT NULL,
    event_id character varying(120) NOT NULL
);

ALTER TABLE public.processed_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processed_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.outbox
    ADD CONSTRAINT outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT processed_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.processed_events
    ADD CONSTRAINT uk_handler_event UNIQUE (handler, event_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk_idempotency_key UNIQUE (idempotency_key);

CREATE INDEX idx_batch_id ON public.payments USING btree (batch_id);

CREATE INDEX idx_state ON public.payments USING btree (state);

