-- Baseline schema for AccountService, generated from the JPA entities.
-- Schema changes go in new V2__..., V3__... files; never edit an applied migration.

CREATE TABLE public.account (
    balance numeric(19,2) NOT NULL,
    currency character varying(3) NOT NULL,
    version integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id uuid NOT NULL,
    account_number character varying(20) NOT NULL,
    display_name character varying(64),
    nickname character varying(64),
    request_fingerprint character varying(128),
    account_sub_type character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    customer_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT account_account_sub_type_check CHECK (((account_sub_type)::text = ANY ((ARRAY['PERSONAL'::character varying, 'BUSINESS'::character varying])::text[]))),
    CONSTRAINT account_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['CHEQUING'::character varying, 'SAVINGS'::character varying, 'CREDIT'::character varying, 'LOAN'::character varying])::text[]))),
    CONSTRAINT account_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'FROZEN'::character varying, 'CLOSED'::character varying])::text[])))
);

CREATE TABLE public.account_hold (
    amount numeric(19,2) NOT NULL,
    version integer,
    created_at timestamp(6) without time zone,
    release_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    account_id uuid NOT NULL,
    id uuid NOT NULL,
    request_fingerprint character varying(128),
    reason character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT account_hold_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CAPTURED'::character varying, 'RELEASED'::character varying, 'CANCELED'::character varying, 'EXPIRED'::character varying])::text[])))
);

CREATE TABLE public.account_transaction (
    amount numeric(19,2) NOT NULL,
    balance_after numeric(19,2),
    currency character varying(3) NOT NULL,
    version integer,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    account_id uuid NOT NULL,
    transaction_id uuid NOT NULL,
    status character varying(32) NOT NULL,
    type character varying(32) NOT NULL,
    request_fingerprint character varying(100),
    reason character varying(256),
    CONSTRAINT account_transaction_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'POSTED'::character varying, 'REVERSED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT account_transaction_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying, 'HOLD_PLACED'::character varying, 'HOLD_RELEASED'::character varying])::text[])))
);

ALTER TABLE public.account_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_account_number_key UNIQUE (account_number);

ALTER TABLE ONLY public.account_hold
    ADD CONSTRAINT account_hold_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_hold
    ADD CONSTRAINT account_hold_request_fingerprint_key UNIQUE (request_fingerprint);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_request_fingerprint_key UNIQUE (request_fingerprint);

ALTER TABLE ONLY public.account_transaction
    ADD CONSTRAINT account_transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_transaction
    ADD CONSTRAINT account_transaction_transaction_id_key UNIQUE (transaction_id);

ALTER TABLE ONLY public.account_transaction
    ADD CONSTRAINT uk_tx_account_idem UNIQUE (account_id, request_fingerprint);

CREATE INDEX idx_account_customer ON public.account USING btree (customer_id);

CREATE INDEX idx_account_status ON public.account USING btree (status);

CREATE INDEX idx_hold_account ON public.account_hold USING btree (account_id);

CREATE INDEX idx_hold_status ON public.account_hold USING btree (status);

CREATE INDEX idx_tx_account ON public.account_transaction USING btree (account_id);

CREATE INDEX idx_tx_occurred ON public.account_transaction USING btree (occurred_at);

CREATE INDEX idx_tx_status ON public.account_transaction USING btree (status);

CREATE INDEX idx_tx_type ON public.account_transaction USING btree (type);

