-- Baseline schema for CustomerService, generated from the JPA entities.
-- Schema changes go in new V2__..., V3__... files; never edit an applied migration.

CREATE TABLE public.customers (
    active boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    address character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    external_id character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    kyc_status character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone character varying(255),
    request_fingerprint character varying(255) NOT NULL,
    CONSTRAINT customers_kyc_status_check CHECK (((kyc_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT uniq_customers_email UNIQUE (email);

