server:
  port: 8094

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
  application:
    name: auth-user

  jackson:
    serialization:
      INDENT_OUTPUT: false

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST"

consent:
  service:
    url: ${CONSENT_SERVICE_URL}

auth0:
  domain: ${AUTH0_DOMAIN}
  audience: ${AUTH0_AUDIENCE}
  customer-role-id: ${AUTH0_CUSTOMER_ROLE_ID}
  mgmt:
    client-id: ${AUTH0_MGMT_CLIENT_ID}
    client-secret: ${AUTH0_MGMT_CLIENT_SECRET}
    audience: ${AUTH0_DOMAIN}/api/v2/
